### PR TITLE
Initial draft of Chapter 4

### PR DESCRIPTION
**Pull request by WilliamJamieson**
First draft of chapter 4 workbook

### CODE REVIEW

**Comment by zacharyburnett** [comment]
I added a notebook run check to the CI but I'm not sure why it's not running for this PR

**Comment by WilliamJamieson** [comment]
Trying to close and reopen.

**Comment by WilliamJamieson** [comment]
> I added a notebook run check to the CI but I'm not sure why it's not running for this PR

You as the admin/maintainer may need to authorize my PR to run?

**Review by zacharyburnett — APPROVED** [review]

**Comment by zacharyburnett** [comment]
I ran the check manually and it seems to pass:
```shell
python -m nbcollection execute .
```
```
[nbcollection (INFO)]: Collected 1 notebook files
[nbcollection (INFO)]: Finished running notebook '04-Creating_ASDF_Files.ipynb' (3.60 seconds) ✅
```

**Comment by zacharyburnett** [comment]
@WilliamJamieson with a rebase of the recent commit, the check now executes successfully.

**Comment by WilliamJamieson** [comment]
Did you mean to merge this?

**Comment by zacharyburnett** [comment]
> Did you mean to merge this?

oh yes, sorry, you marked it as ready for review so I approved and merged it. I can undo that if you are still working on it

**Comment by WilliamJamieson** [comment]
Please undo the merge.

**Comment by zacharyburnett** [comment]
ok, I reverted the merge commit, you should be able to push a commit to this branch and it should reopen

**Comment by WilliamJamieson** [comment]
Okay the push did not reopen the PR.

**Pull request merged**
